import { db } from "../lib/database";
import { countries, complianceRules, users } from "@shared/schema";
import { createChildLogger } from "../lib/logger";

const logger = createChildLogger('seed');

const countryData = [
  {
    name: "United States",
    iso: "US",
    region: "North America",
    population: 331900000,
    gdpPerCapita: 70248,
    currencyCode: "USD",
    languages: ["English"],
    timeZone: "UTC-5",
    legalSystem: "Common Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 92,
    taxComplexity: 7,
    laborLaws: "Comprehensive federal and state labor protections",
    dataPrivacy: "Strong privacy laws with sector-specific regulations",
    featured: true,
    lastUpdated: new Date(),
  },
  {
    name: "United Kingdom", 
    iso: "GB",
    region: "Europe",
    population: 67500000,
    gdpPerCapita: 46344,
    currencyCode: "GBP",
    languages: ["English"],
    timeZone: "UTC+0",
    legalSystem: "Common Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 95,
    taxComplexity: 6,
    laborLaws: "Strong worker protections under Employment Rights Act",
    dataPrivacy: "UK GDPR provides comprehensive data protection",
    featured: true,
    lastUpdated: new Date(),
  },
  {
    name: "Germany",
    iso: "DE", 
    region: "Europe",
    population: 83200000,
    gdpPerCapita: 50801,
    currencyCode: "EUR",
    languages: ["German"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 97,
    taxComplexity: 8,
    laborLaws: "Strict employment protections and co-determination rights",
    dataPrivacy: "GDPR compliance with additional German privacy laws",
    featured: true,
    lastUpdated: new Date(),
  },
  {
    name: "Canada",
    iso: "CA",
    region: "North America", 
    population: 38200000,
    gdpPerCapita: 52051,
    currencyCode: "CAD",
    languages: ["English", "French"],
    timeZone: "UTC-5",
    legalSystem: "Common Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 94,
    taxComplexity: 6,
    laborLaws: "Federal and provincial employment standards",
    dataPrivacy: "PIPEDA provides strong privacy protections",
    featured: true,
    lastUpdated: new Date(),
  },
  {
    name: "Australia",
    iso: "AU",
    region: "Oceania",
    population: 25700000,
    gdpPerCapita: 54907,
    currencyCode: "AUD", 
    languages: ["English"],
    timeZone: "UTC+10",
    legalSystem: "Common Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 91,
    taxComplexity: 7,
    laborLaws: "Fair Work Act provides comprehensive protections",
    dataPrivacy: "Privacy Act with mandatory breach notification",
    featured: true,
    lastUpdated: new Date(),
  },
  {
    name: "Netherlands",
    iso: "NL",
    region: "Europe",
    population: 17400000,
    gdpPerCapita: 56489,
    currencyCode: "EUR",
    languages: ["Dutch"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 96,
    taxComplexity: 7,
    laborLaws: "Strong worker protections with flexible arrangements",
    dataPrivacy: "GDPR implementation with Dutch privacy authority oversight",
    featured: true,
    lastUpdated: new Date(),
  },
  {
    name: "Singapore",
    iso: "SG",
    region: "Asia",
    population: 5900000,
    gdpPerCapita: 72795,
    currencyCode: "SGD",
    languages: ["English", "Mandarin", "Malay", "Tamil"],
    timeZone: "UTC+8",
    legalSystem: "Common Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "wise"] as const,
    complianceScore: 88,
    taxComplexity: 5,
    laborLaws: "Employment Act with recent updates for gig workers",
    dataPrivacy: "Personal Data Protection Act (PDPA)",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Japan",
    iso: "JP", 
    region: "Asia",
    population: 125800000,
    gdpPerCapita: 39285,
    currencyCode: "JPY",
    languages: ["Japanese"],
    timeZone: "UTC+9",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 85,
    taxComplexity: 9,
    laborLaws: "Labor Standards Act with lifetime employment culture",
    dataPrivacy: "Personal Information Protection Act",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "France",
    iso: "FR",
    region: "Europe", 
    population: 67750000,
    gdpPerCapita: 43518,
    currencyCode: "EUR",
    languages: ["French"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 89,
    taxComplexity: 9,
    laborLaws: "Code du travail with strong employee protections",
    dataPrivacy: "GDPR with additional French data protection laws",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Brazil",
    iso: "BR",
    region: "South America",
    population: 215300000,
    gdpPerCapita: 8845,
    currencyCode: "BRL",
    languages: ["Portuguese"],
    timeZone: "UTC-3",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 72,
    taxComplexity: 10,
    laborLaws: "CLT provides extensive worker rights and protections",
    dataPrivacy: "LGPD (Brazilian GDPR) with strict compliance requirements",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "India",
    iso: "IN",
    region: "Asia",
    population: 1380000000,
    gdpPerCapita: 2256,
    currencyCode: "INR",
    languages: ["Hindi", "English"],
    timeZone: "UTC+5:30",
    legalSystem: "Common Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "wise"] as const,
    complianceScore: 75,
    taxComplexity: 8,
    laborLaws: "Industrial Relations Code and related labor reforms",
    dataPrivacy: "Digital Personal Data Protection Act 2023",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "South Korea",
    iso: "KR",
    region: "Asia", 
    population: 51780000,
    gdpPerCapita: 31846,
    currencyCode: "KRW",
    languages: ["Korean"],
    timeZone: "UTC+9",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 83,
    taxComplexity: 7,
    laborLaws: "Labor Standards Act with recent flexibility improvements",
    dataPrivacy: "Personal Information Protection Act (PIPA)",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Mexico",
    iso: "MX",
    region: "North America",
    population: 128900000,
    gdpPerCapita: 10405,
    currencyCode: "MXN", 
    languages: ["Spanish"],
    timeZone: "UTC-6",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 69,
    taxComplexity: 8,
    laborLaws: "Federal Labor Law with recent reforms",
    dataPrivacy: "Federal Law on Protection of Personal Data",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Argentina",
    iso: "AR",
    region: "South America",
    population: 45400000,
    gdpPerCapita: 10636,
    currencyCode: "ARS",
    languages: ["Spanish"],
    timeZone: "UTC-3",
    legalSystem: "Civil Law",
    riskLevel: "high" as const,
    contractorTypes: ["employee"] as const,
    paymentMethods: ["bank_transfer"] as const,
    complianceScore: 58,
    taxComplexity: 9,
    laborLaws: "Strict labor laws with high employment protection",
    dataPrivacy: "Personal Data Protection Law with regulatory challenges",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "China",
    iso: "CN",
    region: "Asia",
    population: 1439000000,
    gdpPerCapita: 12556,
    currencyCode: "CNY",
    languages: ["Mandarin"],
    timeZone: "UTC+8",
    legalSystem: "Civil Law",
    riskLevel: "high" as const,
    contractorTypes: ["employee"] as const,
    paymentMethods: ["bank_transfer"] as const,
    complianceScore: 45,
    taxComplexity: 8,
    laborLaws: "Labor Contract Law with strict compliance requirements",
    dataPrivacy: "Cybersecurity Law and Data Security Law",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Russia",
    iso: "RU",
    region: "Europe/Asia",
    population: 146000000,
    gdpPerCapita: 11654,
    currencyCode: "RUB",
    languages: ["Russian"],
    timeZone: "UTC+3",
    legalSystem: "Civil Law",
    riskLevel: "high" as const,
    contractorTypes: ["employee"] as const,
    paymentMethods: ["bank_transfer"] as const,
    complianceScore: 35,
    taxComplexity: 7,
    laborLaws: "Labor Code with complex regulatory environment",
    dataPrivacy: "Federal Law on Personal Data with localization requirements",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Iran",
    iso: "IR",
    region: "Middle East",
    population: 84000000,
    gdpPerCapita: 3346,
    currencyCode: "IRR",
    languages: ["Persian"],
    timeZone: "UTC+3:30",
    legalSystem: "Islamic Law",
    riskLevel: "high" as const,
    contractorTypes: [] as const,
    paymentMethods: [] as const,
    complianceScore: 15,
    taxComplexity: 6,
    laborLaws: "Labor Law within Islamic jurisprudence framework",
    dataPrivacy: "Limited data protection framework",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "North Korea",
    iso: "KP",
    region: "Asia",
    population: 25800000,
    gdpPerCapita: 648,
    currencyCode: "KPW",
    languages: ["Korean"],
    timeZone: "UTC+9",
    legalSystem: "Socialist Law",
    riskLevel: "high" as const,
    contractorTypes: [] as const,
    paymentMethods: [] as const,
    complianceScore: 5,
    taxComplexity: 3,
    laborLaws: "State-controlled labor system",
    dataPrivacy: "No recognized data protection framework",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Switzerland",
    iso: "CH",
    region: "Europe",
    population: 8700000,
    gdpPerCapita: 83717,
    currencyCode: "CHF",
    languages: ["German", "French", "Italian"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 98,
    taxComplexity: 6,
    laborLaws: "Federal and cantonal employment laws with high flexibility",
    dataPrivacy: "Federal Act on Data Protection (nFADP)",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Sweden",
    iso: "SE",
    region: "Europe",
    population: 10400000,
    gdpPerCapita: 54608,
    currencyCode: "SEK",
    languages: ["Swedish"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 96,
    taxComplexity: 7,
    laborLaws: "Employment Protection Act with collective bargaining",
    dataPrivacy: "GDPR with Swedish Privacy Protection Authority oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Norway",
    iso: "NO",
    region: "Europe", 
    population: 5400000,
    gdpPerCapita: 75420,
    currencyCode: "NOK",
    languages: ["Norwegian"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 97,
    taxComplexity: 6,
    laborLaws: "Working Environment Act with strong worker protections",
    dataPrivacy: "Personal Data Act implementing GDPR",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Denmark",
    iso: "DK",
    region: "Europe",
    population: 5800000,
    gdpPerCapita: 60170,
    currencyCode: "DKK",
    languages: ["Danish"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 95,
    taxComplexity: 7,
    laborLaws: "Flexible employment with strong social safety net",
    dataPrivacy: "GDPR with Danish Data Protection Agency oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Finland",
    iso: "FI",
    region: "Europe",
    population: 5500000,
    gdpPerCapita: 48810,
    currencyCode: "EUR",
    languages: ["Finnish", "Swedish"],
    timeZone: "UTC+2",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "stripe", "wise"] as const,
    complianceScore: 96,
    taxComplexity: 7,
    laborLaws: "Employment Contracts Act with high worker protections",
    dataPrivacy: "Data Protection Act implementing GDPR",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Italy",
    iso: "IT",
    region: "Europe",
    population: 60400000,
    gdpPerCapita: 35551,
    currencyCode: "EUR",
    languages: ["Italian"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 79,
    taxComplexity: 9,
    laborLaws: "Workers' Statute with complex regulatory framework",
    dataPrivacy: "GDPR with Italian Data Protection Authority oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Spain",
    iso: "ES",
    region: "Europe",
    population: 47400000,
    gdpPerCapita: 29565,
    currencyCode: "EUR", 
    languages: ["Spanish"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 81,
    taxComplexity: 8,
    laborLaws: "Workers' Statute with strong employment protections",
    dataPrivacy: "GDPR with Spanish Data Protection Agency oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Poland",
    iso: "PL",
    region: "Europe",
    population: 38000000,
    gdpPerCapita: 17840,
    currencyCode: "PLN",
    languages: ["Polish"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "wise"] as const,
    complianceScore: 84,
    taxComplexity: 7,
    laborLaws: "Labor Code with EU-aligned employment rights",
    dataPrivacy: "GDPR with Personal Data Protection Office oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Czech Republic",
    iso: "CZ",
    region: "Europe",
    population: 10700000,
    gdpPerCapita: 26821,
    currencyCode: "CZK",
    languages: ["Czech"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "low" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "wise"] as const,
    complianceScore: 87,
    taxComplexity: 6,
    laborLaws: "Labor Code with EU compliance standards",
    dataPrivacy: "GDPR with Czech Data Protection Office oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Hungary",
    iso: "HU",
    region: "Europe",
    population: 9700000,
    gdpPerCapita: 18773,
    currencyCode: "HUF",
    languages: ["Hungarian"],
    timeZone: "UTC+1",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 78,
    taxComplexity: 7,
    laborLaws: "Labor Code with recent flexibility reforms",
    dataPrivacy: "GDPR with Hungarian Data Protection Authority oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Romania",
    iso: "RO",
    region: "Europe",
    population: 19200000,
    gdpPerCapita: 14858,
    currencyCode: "RON",
    languages: ["Romanian"],
    timeZone: "UTC+2",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "wise"] as const,
    complianceScore: 76,
    taxComplexity: 7,
    laborLaws: "Labor Code aligned with EU employment directives",
    dataPrivacy: "GDPR with Romanian Data Protection Authority oversight",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Ukraine",
    iso: "UA",
    region: "Europe",
    population: 44100000,
    gdpPerCapita: 4836,
    currencyCode: "UAH",
    languages: ["Ukrainian"],
    timeZone: "UTC+2",
    legalSystem: "Civil Law",
    riskLevel: "high" as const,
    contractorTypes: ["employee"] as const,
    paymentMethods: ["bank_transfer"] as const,
    complianceScore: 42,
    taxComplexity: 8,
    laborLaws: "Labor Code under wartime modifications",
    dataPrivacy: "Law on Personal Data Protection with EU alignment efforts",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "Turkey",
    iso: "TR",
    region: "Europe/Asia",
    population: 84300000,
    gdpPerCapita: 9539,
    currencyCode: "TRY",
    languages: ["Turkish"],
    timeZone: "UTC+3",
    legalSystem: "Civil Law",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor"] as const,
    paymentMethods: ["bank_transfer", "wise"] as const,
    complianceScore: 68,
    taxComplexity: 8,
    laborLaws: "Labor Law with social security requirements",
    dataPrivacy: "Personal Data Protection Law (KVKK)",
    featured: false,
    lastUpdated: new Date(),
  },
  {
    name: "South Africa",
    iso: "ZA",
    region: "Africa",
    population: 59300000,
    gdpPerCapita: 7055,
    currencyCode: "ZAR",
    languages: ["English", "Afrikaans", "Zulu", "Xhosa"],
    timeZone: "UTC+2",
    legalSystem: "Mixed (Roman-Dutch & Common Law)",
    riskLevel: "medium" as const,
    contractorTypes: ["employee", "contractor", "freelancer"] as const,
    paymentMethods: ["bank_transfer", "paypal", "wise"] as const,
    complianceScore: 73,
    taxComplexity: 8,
    laborLaws: "Labour Relations Act with strong worker protections",
    dataPrivacy: "Protection of Personal Information Act (POPIA)",
    featured: false,
    lastUpdated: new Date(),
  },
];

const sampleRules = [
  {
    countryId: "", // Will be filled during seeding
    title: "Employee Classification Requirements",
    description: "Guidelines for properly classifying workers as employees vs contractors",
    ruleType: "classification" as const,
    category: "employment" as const,
    severity: 8,
    requirements: ["Written contracts required", "Clear scope of work definition", "Regular review of worker status"],
    penalties: "Fines up to $50,000 per misclassified worker",
    effectiveFrom: new Date("2024-01-01"),
    effectiveTo: new Date("2024-12-31"),
    lastUpdated: new Date("2024-01-15"),
    source: "Department of Labor Guidelines 2024",
    status: "published" as const,
  },
  {
    countryId: "",
    title: "Data Privacy Compliance", 
    description: "Requirements for handling contractor personal data",
    ruleType: "privacy" as const,
    category: "data_privacy" as const,
    severity: 9,
    requirements: ["Explicit consent for data collection", "Data minimization principles", "Right to deletion implementation"],
    penalties: "Up to 4% of annual revenue or €20 million",
    effectiveFrom: new Date("2024-01-01"),
    effectiveTo: new Date("2024-12-31"),
    lastUpdated: new Date("2024-02-20"),
    source: "GDPR Article 83",
    status: "published" as const,
  },
  {
    countryId: "",
    title: "Tax Withholding Requirements",
    description: "Obligations for tax withholding on contractor payments", 
    ruleType: "tax" as const,
    category: "tax" as const,
    severity: 7,
    requirements: ["Form W-9 collection", "1099 reporting for payments >$600", "Quarterly estimated tax guidance"],
    penalties: "24% backup withholding rate",
    effectiveFrom: new Date("2024-01-01"),
    effectiveTo: new Date("2024-12-31"),
    lastUpdated: new Date("2024-03-10"),
    source: "IRS Publication 15-A",
    status: "published" as const,
  },
];

async function seedDatabase() {
  try {
    logger.info("Starting database seed...");
    
    // Clear existing data
    await db.delete(complianceRules);
    await db.delete(countries);
    
    // Insert countries
    logger.info("Seeding countries...");
    const insertedCountries = await db.insert(countries).values(countryData).returning();
    logger.info(`Inserted ${insertedCountries.length} countries`);
    
    // Insert sample compliance rules for major countries
    logger.info("Seeding compliance rules...");
    const majorCountries = insertedCountries.filter(c => ["US", "GB", "DE", "CA"].includes(c.iso));
    
    const rulePromises = majorCountries.flatMap(country => 
      sampleRules.map(rule => ({
        ...rule,
        countryId: country.id,
      }))
    );
    
    const insertedRules = await db.insert(complianceRules).values(rulePromises).returning();
    logger.info(`Inserted ${insertedRules.length} compliance rules`);
    
    // Create admin user
    logger.info("Creating admin user...");
    const adminUsers = await db.insert(users).values([{
      username: "admin",
      email: "admin@deel.com", 
      password: "admin123", // In production, this should be hashed
      role: "admin" as const,
      createdAt: new Date(),
    }]).returning();
    logger.info(`Created ${adminUsers.length} admin users`);
    
    logger.info("Database seeding completed successfully!");
    
  } catch (error) {
    logger.error("Database seeding failed:", error);
    throw error;
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedDatabase()
    .then(() => {
      console.log("✅ Database seeded successfully");
      process.exit(0);
    })
    .catch((error) => {
      console.error("❌ Database seeding failed:", error);
      process.exit(1);
    });
}

export { seedDatabase };